services:
  db:
    container_name: postgres-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: d17_map
      POSTGRES_USER: d17_map
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - ktor-postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U d17_map" ]
    env_file:
      - .env

  web:
    container_name: ktor-server
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ktor-postgres

volumes:
  db-data: {}

networks:
  ktor-postgres: {}
