### GET request to retrieve all classrooms
GET http://localhost:8080/classrooms
Accept: application/json

### POST request to create a new classroom
POST http://localhost:8080/classrooms
Content-Type: application/json

{
  "name": "Classroom A",
  "capacity": 30,
  "description": "Description for classroom A"
}

### Retrieve classroomId from the POST response
@classroomId = {{last.response.body.id}}

### GET request to retrieve a classroom by ID
GET http://localhost:8080/classrooms/{{classroomId}}
Accept: application/json

### PUT request to update an existing classroom
PUT http://localhost:8080/classrooms/{{classroomId}}
Content-Type: application/json

{
  "name": "Updated Classroom A",
  "capacity": 40,
  "description": "Updated Description for classroom A"
}

### DELETE request to delete a classroom by ID
DELETE http://localhost:8080/classrooms/{{classroomId}}

###
