### ID of the User
@userId = 7f000001-92aa-1b92-8192-aaebf21c0000
### Day of existing reservation
@day = 2024-10-10

### Reservation id of existing reservation
@reservationId = 7f000001-92aa-1b92-8192-aaed06af0005

### Classroom id of existing classroom
@classroomId = 7f000001-92aa-1b92-8192-aaec3d620001

### Monday date
@monday = 2024-10-14

### GET request to retrieve reservations by day (with valid date)
GET http://localhost:8080/reservations?day=2024-10-10
Accept: application/json

### POST request to create a new reservation
POST http://localhost:8080/reservations
Content-Type: application/json

{
  "userId": "{{userId}}",
  "classroomId": "{{classroomId}}",
  "date": "2024-10-16",
  "startTime": "09:00",
  "endTime": "10:30",
  "title": "Example Reservation for test",
  "type": "CLASS"}

### GET request to retrieve reservations by id
GET http://localhost:8080/reservations/{{reservationId}}
Accept: application/json

### GET request to retrieve future reservations for a user by user ID
GET http://localhost:8080/reservations/{{userId}}/future-reservations
Accept: application/json

### GET request to retrieve reservation by ID
GET http://localhost:8080/reservations/{{reservationId}}
Accept: application/json

### GET request to retrieve all reservations for given week
GET http://localhost:8080/reservations/week?startOfTheWeek={{monday}}
Accept: application/json

### GET request to retrieve reservations for user for the week
GET http://localhost:8080/reservations/{{userId}}/week
Accept: application/json

###

