### Register user
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "{{registered_user}}",
  "password": "{{registered_user_pass}}"
}

### Log in to the application
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "{{registered_user}}",
  "password": "{{registered_user_pass}}"
}

> {%
    client.global.set("jwt_token", response.body);
%}
