name: Build and Test on Push to EVIL-* branches

on:
  push:
    branches:
      - 'EVIL-*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and run tests
        run: mvn clean test
