name: D17Map build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java SDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up environment variables
        run: |
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker images
        run: |
          docker-compose build --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD

      - name: Start Docker containers
        run: docker-compose up -d

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ktor-docker-sample.jar
          path: /app/ktor-docker-sample.jar
